const sampleData = {
  products: [
    {
      name: "Crochet Mobile Bag",
      slug: "Crochet-mobile-bag",
      category: "Women's mobile bag",
      description: "Classic modern side mobile bag",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
        "/images/sample-products/p1-3.jpg",
      ],
      price: 20.5,
      brand: "Crochet",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Crochet women's side Bag",
      slug: "Crochet-women's-side-Bag",
      category: "Women's mobile side bag",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
        "/images/sample-products/p2-3.jpg",
      ],
      price: 32.8,
      brand: "Crochet",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Side water bottle Sling bag",
      slug: "Side-water-bottle-Sling-bag",
      category: "Water bottle bag",
      description: "Modern classic sling bag",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
        "/images/sample-products/p3-3.jpg",
        "/images/sample-products/p3-4.jpg",
      ],
      price: 8,
      brand: "Crochet",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Womens side bag",
      slug: "Womens-side-bag",
      category: "Women's side bag",
      description: "Streamlined design with flexible stretch",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
        "/images/sample-products/p4-3.jpg",
        "/images/sample-products/p4-4.jpg",
      ],
      price: 5,
      brand: "Crochet",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Girls baby crochet cloths",
      slug: "Girls-baby-crochet-cloths",
      category: "Girls baby crochet cloths",
      description: "Dress fully made by Crochet",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
        "/images/sample-products/p5-3.jpg",
      ],
      price: 8,
      brand: "Crochet",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Crochet Keychain and Money holder",
      slug: "Crochet-Keychain-and-Money-holder",
      category: "Keychain and Money bag",
      description: "Soft, stylish, and perfect for money holder",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
        "/images/sample-products/p6-3.jpg",
      ],
      price: 7,
      brand: "Crochet",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
