import { hashSync } from "bcrypt-ts-edge";
const sampleData = {
  users: [
    {
      name: "Ziaul",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "ziaulbe",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "Crochet Mobile Bag",
      slug: "Crochet-mobile-bag",
      category: "Women's mobile bag",
      description: "Classic modern side mobile bag",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
        "/images/sample-products/p1-3.jpg",
      ],
      price: 20.5,
      brand: "Crochet",
      rating: 4.5,
      numReviews: 10,
      stock: 1,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Crochet women's side Bag",
      slug: "Crochet-women's-side-Bag",
      category: "Women's mobile side bag",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
        "/images/sample-products/p2-3.jpg",
      ],
      price: 35.0,
      brand: "Crochet",
      rating: 4.2,
      numReviews: 8,
      stock: 1,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Side water bottle Sling bag",
      slug: "Side-water-bottle-Sling-bag",
      category: "Water bottle bag",
      description: "Modern classic sling bag",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
        "/images/sample-products/p3-3.jpg",
        "/images/sample-products/p3-4.jpg",
      ],
      price: 10.0,
      brand: "Crochet",
      rating: 4.9,
      numReviews: 3,
      stock: 1,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Womens side bag",
      slug: "Womens-side-bag",
      category: "Women's side bag",
      description: "Streamlined design with flexible stretch",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
        "/images/sample-products/p4-3.jpg",
        "/images/sample-products/p4-4.jpg",
      ],
      price: 30.0,
      brand: "Crochet",
      rating: 3.6,
      numReviews: 5,
      stock: 1,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Girls baby crochet cloths",
      slug: "Girls-baby-crochet-cloths",
      category: "Girls baby crochet cloths",
      description: "Dress fully made by Crochet",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
        "/images/sample-products/p5-3.jpg",
      ],
      price: 25.0,
      brand: "Crochet",
      rating: 4.7,
      numReviews: 18,
      stock: 1,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Crochet Keychain and Money holder",
      slug: "Crochet-Keychain-and-Money-holder",
      category: "Keychain and Money bag",
      description: "Soft, stylish, and perfect for money holder",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
        "/images/sample-products/p6-3.jpg",
      ],
      price: 15.0,
      brand: "Crochet",
      rating: 4.6,
      numReviews: 12,
      stock: 1,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Shoulder bag",
      slug: "Shoulder-bag",
      category: "Shoulder bag",
      description: "Soft, stylish, and perfect for women",
      images: [
        "/images/sample-products/p7-1.jpg",
        "/images/sample-products/p7-2.jpg",
        "/images/sample-products/p7-3.jpg",
        "/images/sample-products/p7-4.jpg",
      ],
      price: 70,
      brand: "Crochet",
      rating: 4.6,
      numReviews: 12,
      stock: 1,
      isFeatured: true,
      banner: null,
    },
    {
      name: "mobile bag",
      slug: "mobile-bag",
      category: "mobile bag",
      description: "Soft, stylish, and perfect for women",
      images: [
        "/images/sample-products/p8-1.jpg",
        "/images/sample-products/p8-2.jpg",
        "/images/sample-products/p8-3.jpg",
      ],
      price: 10,
      brand: "Crochet",
      rating: 4.6,
      numReviews: 12,
      stock: 1,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Sea shell bag with zip",
      slug: "Sea-shell-bag-with-zip",
      category: "Sea shell bag with zip",
      description: "Soft, stylish, and perfect for women",
      images: [
        "/images/sample-products/p9-1.jpg",
        "/images/sample-products/p9-2.jpg",
        "/images/sample-products/p9-3.jpg",
      ],
      price: 15,
      brand: "Crochet",
      rating: 4.6,
      numReviews: 12,
      stock: 1,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
