const sampleData = {
  products: [
    {
      name: "Handcraft Mobile Bag",
      slug: "handcraft-mobile-bag",
      category: "Women's mobile bag",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
        "/images/sample-products/p1-3.jpg",
      ],
      price: 20.5,
      brand: "Crochet",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Handcraft Shoulder Bag",
      slug: "handcraft-shoulder-bag",
      category: "Women's mobile side bag",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
        "/images/sample-products/p2-3.jpg",
      ],
      price: 32.8,
      brand: "Crochet",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Side Bag Sling",
      slug: "side-bag-sling",
      category: "Women's sling bag",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
        "/images/sample-products/p3-3.jpg",
        "/images/sample-products/p3-4.jpg",
      ],
      price: 8,
      brand: "Crochet",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Hair Band",
      slug: "hair-band",
      category: "Women's hair band",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
        "/images/sample-products/p4-3.jpg",
        "/images/sample-products/p4-4.jpg",
      ],
      price: 5,
      brand: "Crochet",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Sidebag Sling",
      slug: "sidebag-sling",
      category: "Women's side bag sling",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
        "/images/sample-products/p5-3.jpg",
      ],
      price: 8,
      brand: "Crochet",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Bag Keychain",
      slug: "bag-keychain",
      category: "keychain for bag",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
        "/images/sample-products/p6-3.jpg",
      ],
      price: 7,
      brand: "Crochet",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
